### ISSUE TITLE
Zeus image improperly being rendered 

### ISSUE THREAD

**Issue by vbedesu** [TeamSCALEFORM/scaleform#20]
## System Information
**OS: Microsoft Windows 10 x64 LTSC 21H2**  
**DE: explorer.exe**
**WM: dwm.exe**  
**ScaleForm Ver. latest git commit from Jul 30, 2022, 02:29 AM**

## Description
The Zeus X27 image is not properly being rendered, it gets cut whenever you wear it or not.

## Steps to reproduce  
Inject ScaleForm, go onto a CS:GO match and purchase the Zeus X27

## Image
![image](https://user-images.githubusercontent.com/99480390/182201166-c2629016-de35-4d68-9bea-6fcfa16bafc9.png)

**Comment by cristeigabriel** [comment]
@smevold check this out
