### ISSUE TITLE
Images for HUD do not load.

### ISSUE THREAD

**Issue by v4llu** [TeamSCALEFORM/scaleform#43]
When I inject the ScaleForm.dll to csgo.exe with the `-insecure` parameter it doesn't load the images at all.
Not sure if its on my end, Due to me having poor coding skills in general or following instructions.

**Issue:**
![Counter-strike  Global Offensive Screenshot 2023 05 18 - 00 03 04 29](https://github.com/TeamSCALEFORM/scaleform/assets/127980435/a3a3759e-e75d-4bcf-8009-9b6ddbf2487f)

**Comment by Patoke** [comment]
When accessing the images directly from [here](https://github.com/TeamSCALEFORM/scaleform/blob/main/scaleform/winpanel.js#LL9C37-L9C84) they load normally meaning the host isn't down
Maybe you were trying to use this without an internet connection?
Remember to not modify these links and if you're gonna do personal use of this project make sure to host them yourself and make sure the host doesn't rate limit requests to get the image data (You can also host them in your CS:GO game files so this won't be a problem but you would need to place them in the appropiate directories)

Make sure your internet is up and running when using the project and make sure the image hosts aren't down

If this is a custom implementation of this code inside of another project then there's nothing we can do to help you fix this other than to point out common issues that might cause this behaviour

**Comment by v4llu** [comment]
Since I tried it with a NoSteam version of CS:GO, It doesn't load any images.
Instead the Normal version of CS:GO loads the images as usual?
I used `-insecure` in both of these.
Not sure how this happens, Might be related to a Steam connection possibly?

### Regular CS:GO
![Counter-strike  Global Offensive Screenshot 2023 05 18 - 16 19 23 86](https://github.com/TeamSCALEFORM/scaleform/assets/127980435/f9c57e25-b027-49e4-b2bd-1f0b6807ae73)

### NoSteam CS:GO
![Counter-strike  Global Offensive Screenshot 2023 05 18 - 16 24 46 49](https://github.com/TeamSCALEFORM/scaleform/assets/127980435/96583814-ed30-4117-aeb4-d2da61aadba9)

**Comment by cristeigabriela** [comment]
Hello!

Consider not using NoSteam CS:GO. That appears to fix it.

Best Regards,
Gabriel.
